Repository DDalkkug/DDalkkug-BE, pull requests merged in 2025-06, with the labels that each got.

#3 [FEAT] 회원가입, 로그인, 이메일인증 기능 구현
  build.gradle
  src/main/java/com/drumtong/backend/api/member/controller/MemberController.java
  src/main/java/com/drumtong/backend/api/member/dto/EmailVerificationCodeRequestDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/EmailVerificationRequestDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/MemberLoginRequestDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/MemberLoginResponseDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/MemberRegisterRequestDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/PasswordResetConfirmDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/PasswordResetRequestDTO.java
  src/main/java/com/drumtong/backend/api/member/dto/UserInfoResponseDTO.java
  src/main/java/com/drumtong/backend/api/member/entity/EmailVerification.java
  src/main/java/com/drumtong/backend/api/member/entity/Member.java
  src/main/java/com/drumtong/backend/api/member/entity/PasswordReset.java
  src/main/java/com/drumtong/backend/api/member/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/drumtong/backend/api/member/jwt/service/JwtService.java
  src/main/java/com/drumtong/backend/api/member/repository/EmailVerificationRepository.java
  src/main/java/com/drumtong/backend/api/member/repository/MemberRepository.java
  src/main/java/com/drumtong/backend/api/member/repository/PasswordResetRepository.java
  src/main/java/com/drumtong/backend/api/member/service/EmailService.java
  src/main/java/com/drumtong/backend/api/member/service/MemberService.java
  src/main/java/com/drumtong/backend/common/config/jwt/JwtConfig.java
  src/main/java/com/drumtong/backend/common/config/mail/MailConfig.java
  src/main/java/com/drumtong/backend/common/config/security/SecurityConfig.java
  src/main/java/com/drumtong/backend/common/config/security/SecurityMember.java
  src/main/java/com/drumtong/backend/common/config/swagger/SwaggerConfig.java
  src/main/java/com/drumtong/backend/common/response/ErrorStatus.java
  src/main/java/com/drumtong/backend/common/response/SuccessStatus.java
Labels: FEAT

#16 [FIX] 닉네임 중복 체크 기능 구현
  src/main/java/com/drumtong/backend/api/member/repository/MemberRepository.java
  src/main/java/com/drumtong/backend/api/member/service/MemberService.java
  src/main/java/com/drumtong/backend/common/response/ErrorStatus.java
Labels: FIX

#17 Refact/#14
  .gitignore
  src/main/java/com/drumtong/backend/api/group/controller/GroupMemberController.java
  src/main/java/com/drumtong/backend/api/group/dto/GroupMemberCommandDto.java
  src/main/java/com/drumtong/backend/api/group/dto/GroupMemberQueryDto.java
  src/main/java/com/drumtong/backend/api/group/entity/GroupMember.java
  src/main/java/com/drumtong/backend/api/group/repository/GroupMemberRepository.java
  src/main/java/com/drumtong/backend/api/group/service/GroupMemberCommandService.java
  src/main/java/com/drumtong/backend/api/group/service/GroupMemberQueryService.java
  src/main/java/com/drumtong/backend/api/groupInfo/controller/GroupInfoController.java
  src/main/java/com/drumtong/backend/api/groupInfo/dto/GroupInfoDto.java
  src/main/java/com/drumtong/backend/api/groupInfo/entity/GroupInfo.java
  src/main/java/com/drumtong/backend/api/groupInfo/repository/GroupInfoRepository.java
  src/main/java/com/drumtong/backend/api/groupInfo/service/GroupInfoCommandService.java
  src/main/java/com/drumtong/backend/api/groupInfo/service/GroupInfoQueryService.java
  src/main/java/com/drumtong/backend/api/member/service/EmailService.java
  src/main/java/com/drumtong/backend/api/member/service/MemberService.java
  src/main/java/com/drumtong/backend/common/response/ErrorStatus.java
Labels: REFAC

#19 [FIX] 이메일 예외처리 메세지 수정
  src/main/java/com/drumtong/backend/api/member/service/EmailService.java
  src/main/java/com/drumtong/backend/api/member/service/MemberService.java
Labels: FIX
